import 'dart:convert';
import 'package:flutter/material.dart';

import 'package:http/http.dart' as http;


class Autogenerated {
  int? response;
  int? code;
  List<Data>? data;

  Autogenerated({this.response, this.code, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    response = json['response'];
    code = json['code'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['response'] = this.response;
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String? id;
  String? imageName;
  String? title;
  String? description;

  Data({this.id, this.imageName, this.title, this.description});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    imageName = json['image_name'];
    title = json['title'];
    description = json['description'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['image_name'] = this.imageName;
    data['title'] = this.title;
    data['description'] = this.description;
    return data;
  }
}




class UserSideBaneeer extends StatefulWidget {
  const UserSideBaneeer({ Key? key }) : super(key: key);

  @override
  State<UserSideBaneeer> createState() => _UserSideBaneeerState();
}

class _UserSideBaneeerState extends State<UserSideBaneeer> {
  @override
  Widget build(BuildContext context) {
    return IssueListApi();
  }
}





class IssueListApi extends StatefulWidget {
  IssueListApi({Key? key}) : super(key: key);

  @override
  State<IssueListApi> createState() => _IssueListApiState();
}

class _IssueListApiState extends State<IssueListApi> {
  Future<Autogenerated> getPostApi() async {
    final response = await http.get(
        Uri.parse("https://dev.noqta-market.com/API/AddBanner.php"));
    var data = jsonDecode(response.body.toString());
    if (response.statusCode == 201) {
      return Autogenerated.fromJson(data);
    } else {
      return Autogenerated.fromJson(data);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
       backgroundColor: Color.fromARGB(230, 0, 0, 0),
    
      body: SafeArea(
        child: Column(
          children: [
      
               
            Column(children: [

              SizedBox(height: 30,),
                  Row(children: [
                      Container(
                     // color: Colors.black,
                        height: 30,
                        width: 30,
                         decoration: BoxDecoration(
            border: Border.all(
              width: 2.0,
              color: Colors.white,
            ),
            borderRadius: BorderRadius.all(
                Radius.circular(18.0) , 
            ),
          ),
        
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                
                children: [
                  SizedBox(width: 5,),
                  GestureDetector(
                    onTap: (){ Navigator.pop(context, );},
                    
                    child: Icon(Icons.arrow_back_ios , color: Colors.white,  size: 16,)),
                    
                ],
                
              ),
              
              
                  
                  
                    ),
                  ],)
        
            ],),
         
            
            SizedBox(height: 30,),
      
            Container(
              height: 300,
              width: double.infinity,
              
              child: FutureBuilder<Autogenerated>(
                    future: getPostApi(),
                    builder: (context, snapshot,) {
      
                      if(snapshot.hasData){
                        return Container(child: Image.network(snapshot.data!.data![0].imageName.toString(), fit: BoxFit.fill,), );
                      }
                      else
                      {return Container();}
                      // ListView.builder(
                      //   itemCount: snapshot.data!.data!.length,
                      //   itemBuilder: (context, index) {
                      //     return Padding(
                      //       padding: const EdgeInsets.only(
                      //           left: 12, right: 12, top: 8),
                      //       child: Column(
                      //         children: [
                      //           Card(
                      //               child: Column(
                      //             children: [
                      //               Row(
                      //                 children: [
                      //                   Padding(
                      //                     padding: const EdgeInsets.all(8.0),
                      //                     child: Column(
                      //                       children: [
                      //                         CircleAvatar(
                      //                           backgroundImage:NetworkImage(snapshot
                      //                               .data!.data![index].imageName
                      //                               .toString()), 
                      //                           radius: 35,
                      //                           backgroundColor: Colors.white,
                      //                         ),
                      //                       ],
                      //                     ),
                      //                   ),
                      //                   Flexible(
                      //                     child: Padding(
                      //                       padding: const EdgeInsets.all(8.0),
                      //                       child: Column(
                      //                         crossAxisAlignment:
                      //                             CrossAxisAlignment.start,
                      //                         children: [
                      //                           Text(snapshot.data!.data![index].title
                      //                               .toString()),
                      //                           Text(snapshot
                      //                               .data!.data![index].description
                      //                               .toString()),
                      //                           Text(snapshot
                      //                               .data!.data![index].id
                      //                               .toString()),
                                               
                      //                         ],
                      //                       ),
                      //                     ),
                      //                   ),
                                       
                      //                 ],
                      //               ),
                      //             ],
                      //           )),
                      //           Container(child: Image.network(snapshot
                      //                               .data!.data![index].imageName
                      //                               .toString()), )
                      //         ],
                      //       ),
                            
                      //     );
                        
                      //   },
                      // );
                      
                    }
                    ),
            
            
            
            )
           
          ],
        ),
      ),
    );
  }
}


// class Upgradetopro extends StatefulWidget {
//   const Upgradetopro({ Key? key }) : super(key: key);

//   @override
//   _UpgradetoproState createState() => _UpgradetoproState();
// }

// class _UpgradetoproState extends State<Upgradetopro> {

//          Future<Autogenerated> getPostApi() async {
//     final response = await http.get(
//         Uri.parse("https://dev.noqta-market.com/API/AddBanner.php"));
//     var data = jsonDecode(response.body.toString());
//     if (response.statusCode == 201) {
//       return Autogenerated.fromJson(data);
//     } else {
//       return Autogenerated.fromJson(data);
//     }
//   }
  

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//     // backgroundColor: Color.fromARGB(230, 0, 0, 0),

//       body: SingleChildScrollView(
//         child: SafeArea(
//           child: Padding(
//             padding: const EdgeInsets.all(12.0),
//             child: Column(children: [
//                Row(children: [
//                  Row(children: [
      
//                      Container(
//                    // color: Colors.black,
//                       height: 30,
//                       width: 30,
//                        decoration: BoxDecoration(
//           border: Border.all(
//             width: 2.0,
//             color: Colors.black,
//           ),
//           borderRadius: BorderRadius.all(
//               Radius.circular(18.0) , 
//           ),
//         ),
      
//             child: Row(
//               mainAxisAlignment: MainAxisAlignment.center,
              
//               children: [
//                 SizedBox(width: 5,),
//                 GestureDetector(
//                   onTap: (){ Navigator.pop(context, );},
                  
//                   child: Icon(Icons.arrow_back_ios , color: Colors.black,  size: 16,)),
//               ],
//             ),
                
                
//                   ),
      
      
//                  ],),
                  
//       SizedBox(width: 50,),
//                  Row(
//                    mainAxisAlignment: MainAxisAlignment.center,
//                    crossAxisAlignment: CrossAxisAlignment.center,
                   
//                    children: [
      
                   
//                  Text(
//                    'Inasta look',
//                   style: GoogleFonts.pacifico(textStyle: TextStyle(color: Colors.black,fontWeight: FontWeight.bold, fontSize: 20,),  )
//                  ),
      
      
//                  ],)
      
      
//                ],),
      
//               //  SizedBox(height: 50,),
//         //  Column(
//         // children: [
//           Expanded(
//               child: FutureBuilder<Autogenerated>(
//                   future: getPostApi(),
//                   builder: (context, snapshot,) {

//                     if(snapshot.hasData){
//                       return Container(child: Image.network(snapshot.data!.data![0].imageName.toString()));
//                     }
//                     else
//                     {return CircularProgressIndicator();}
//                     // ListView.builder(
//                     //   itemCount: snapshot.data!.data!.length,
//                     //   itemBuilder: (context, index) {
//                     //     return Padding(
//                     //       padding: const EdgeInsets.only(
//                     //           left: 12, right: 12, top: 8),
//                     //       child: Column(
//                     //         children: [
//                     //           Card(
//                     //               child: Column(
//                     //             children: [
//                     //               Row(
//                     //                 children: [
//                     //                   Padding(
//                     //                     padding: const EdgeInsets.all(8.0),
//                     //                     child: Column(
//                     //                       children: [
//                     //                         CircleAvatar(
//                     //                           backgroundImage:NetworkImage(snapshot
//                     //                               .data!.data![index].imageName
//                     //                               .toString()), 
//                     //                           radius: 35,
//                     //                           backgroundColor: Colors.white,
//                     //                         ),
//                     //                       ],
//                     //                     ),
//                     //                   ),
//                     //                   Flexible(
//                     //                     child: Padding(
//                     //                       padding: const EdgeInsets.all(8.0),
//                     //                       child: Column(
//                     //                         crossAxisAlignment:
//                     //                             CrossAxisAlignment.start,
//                     //                         children: [
//                     //                           Text(snapshot.data!.data![index].title
//                     //                               .toString()),
//                     //                           Text(snapshot
//                     //                               .data!.data![index].description
//                     //                               .toString()),
//                     //                           Text(snapshot
//                     //                               .data!.data![index].id
//                     //                               .toString()),
                                             
//                     //                         ],
//                     //                       ),
//                     //                     ),
//                     //                   ),
                                     
//                     //                 ],
//                     //               ),
//                     //             ],
//                     //           )),
//                     //           Container(child: Image.network(snapshot
//                     //                               .data!.data![index].imageName
//                     //                               .toString()), )
//                     //         ],
//                     //       ),
                          
//                     //     );
                      
//                     //   },
//                     // );
                    
//                   }
//                   ),
                  
//                   ),
         
//       //   ],
//       // ),
//                SizedBox(height: 15,),
               
                
               
//                 //  Column(children: [
//                 // Row(children: [
                  
//                 //   Icon(Icons.done, color: Colors.green,),
//                 // Text("Giving you the best look of your insta page",style: TextStyle(color: Colors.white, fontSize: 15,),),
      
               
      
      
      
//                 // ],),
//                 // Row(children: [
                  
//                 //   Icon(Icons.done, color: Colors.green,),
//                 // Text("Providing layouts that manage the poor",style: TextStyle(color: Colors.white, fontSize: 15,),),
      
               
      
      
      
//                 // ],),
//                 // ListTile(
//                 //    leading: Icon(Icons.circle_outlined, color: Colors.white,),
//                 //    title:   Text("Aed 9.99/5 pictures Pakage",style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.bold),),
      
      
      
      
//                 // ),
//                 //  ListTile(
//                 //    leading: Icon(Icons.circle_outlined, color: Colors.white,),
//                 //    title:   Text("Aed 22.50/ pictures Pakage",style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.bold),),
      
      
      
      
//                 // ),
//                 //  ListTile(
//                 //    leading: Icon(Icons.circle_outlined, color: Colors.white,),
//                 //    title:   Text("Aed 48.50/ pictures Pakage",style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.bold),),
      
      
      
      
//                 // ),
      
      
//                 //  ],),
      
//               //     Padding(
//               //    padding: const EdgeInsets.only(left: 40,right: 40),
//               //    child: MaterialButton(
//               //    color: Colors.blue,
//               //    minWidth: double.infinity,
//               //    height: 50,
//               //    onPressed: (){
//               //   //   Navigator.push(context, MaterialPageRoute(builder: (context)=> Strip ()));// signup
//               //    },
//               //    shape: RoundedRectangleBorder(
//               //      side: BorderSide(
//               //        color: Colors.blue,
//               //      ),
//               //       borderRadius: BorderRadius.circular(16),
//               //    ),
                 
//               //      child:   Text("Continue",style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.bold),),
                 
      
      
//               //    ),
//               //  ),
                        
                  
            
//             ],),
//           ),
//         ),
//       ),
      
//     );
//   }
// }


